---
- name: MySQL Standalone Installation
  gather_facts: no
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_password: "welcome1"
  tasks:

    - name: install mariadb
      apt:
        name:
          - mariadb-server
          - python3-pymysql
        state: latest

    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started

    - name: mysql_root_password
      mysql_user:
        login_user: ubuntu
        login_password: "{{ mysql_root_password }}"
        user: ubuntu
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost


