---
- name: MySQL Standalone Installation
  gather_facts: false
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes

    - name: "Installing apt dependencies"
      apt:
        name: "{{item}}"
      loop:
        - python-pip
        - python-dev 
        - libmysqlclient-dev

    - name: "Installing pip dependencies"
      pip:
        name: MySQL-python
        extra_args: --index=https://pypi.python.org/pypi/
        version: 1.2.3

    - name: Download and Install mysql
      apt:
        deb: http://repo.mysql.com/mysql-apt-config_0.8.13-1_all.deb

    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'ubuntu'
        login_password: ''
        name: 'ubuntu'
        password: 'welcome1'
        state: present

    - name: Remove the test database
      mysql_db: name=test state=absent
      notify:
        - Restart MySQL
